name: Start SonarQube on EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  start-sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Start SonarQube on EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # Add your EC2 public IP as a secret
          username: ec2-user  # Use the username for your instance type (e.g., ec2-user or ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}  # The SSH private key added as a GitHub secret
          port: 22
          script: |
            sudo su sonar | echo "${{ secrets.SONAR_PASSWORD }}" 
            ls -l
           
